version: "3.8"

services:
  overmorrow:
    container_name: overmorrow
    build: .
    ports:
      - "8096:3000"   # Host port 8096 → Container port 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

